# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: tpluck95/vlsir-test-container
    # Notes on this matrix, particularly the dependencies part:
    # This sets up testing with dependencies from both (a) PyPi and (b) "dev" versions from GitHub.
    # This is particularly relevant for VLSIR, which is often co-developed.
    # Not every version of Hdl21 is designed to work with both.
    # Eventually this should know which *should* work.
    # For now it asserts that the dev-mode passes, and allows failer (`continue-on-error`) for the PyPi version.
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        dep-installer: ["dev", "pypi"]
    continue-on-error: ${{ matrix.dep-installer == 'pypi' }}

    steps:

      - name: Install SKY130 PDK
        run: |
          scripts/install-sky130pdk.sh

      - name: Set up Python ${{ matrix.python-version }}
        run: |
          apt-get install -y python${{ matrix.python-version }}
          apt-get install -y python${{ matrix.python-version }}-dev
          apt-get install -y python${{ matrix.python-version }}-venv
          apt-get install -y python${{ matrix.python-version }}-distutils

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: bash scripts/install-${{ matrix.dep-installer }}.sh

      - name: Test with pytest
        run: |
          pytest -sv --cov=./ --cov-report=xml

      - name: Black Formatting Check
        uses: psf/black@stable
        with:
          version: "22.6"
          options: "--check --diff --verbose --exclude pdks/PdkTemplate"

      - name: Upload coverage to Codecov # Adapted from https://github.com/codecov/codecov-action#usage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
